version: '2'
services:

  app:
    restart: always
    build: ./app
    environment:
      - DB_HOST=redis
      - DB_PORT=6379
      - FLASK_DEBUG=0
    depends_on:
      - redis
    expose:
      - "8000"
    volumes:
      - ./app:/usr/src/app/
    command: /usr/local/bin/gunicorn --reload --log-level info -w 1 -b :8000 app:app

  redis:
    image: redis
    user: redis
    restart: always
    volumes:
      - ./redis-data:/data:rw
    ports:
      - "6379:6379"

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - app
    links:
      - app:app
